version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: veridiapp_user
      POSTGRES_PASSWORD: veridiapp_password
      POSTGRES_DB: veridiapp_user_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U veridiapp_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  user_service:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://veridiapp_user:veridiapp_password@db:5432/veridiapp_user_db
      JWT_SECRET_KEY: dev-secret-key-change-in-production
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 15
      REFRESH_TOKEN_EXPIRE_DAYS: 7
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data:
